### ISSUE TITLE
SilverStripe 3.7 supports PHP 7.2 - so should this module

### ISSUE THREAD

**Issue by NightJar** [bringyourownideas/silverstripe-composer-update-checker#36]
https://github.com/bringyourownideas/silverstripe-composer-update-checker/blob/73e62b1caa6204800a33652a342be8f0018a05d4/composer.json#L34

I think framework's example of `"php": "^5.3.3 || ^7",` should work quite nicely - although we should probably amend it to be `"php": "^5.6.0 || ^7",` for reasons of testing (I think square bracket arrays exist, etc).

**Comment by robbieaverill** [comment]
PHP 7.2 on SilverStripe 3.7 requires extending SS_Object instead of Object, but in order for modules to support this version they need to have a separate version released that extends SS_Object. This is why I haven't done it already, because it's introducing maintenance burden.

If modules don't have any classes that directly extend Object then the constraint can be adjusted to support it easily enough.

I personally don't want to support multiple SilverStripe 3 versions of this module.

**Comment by NightJar** [comment]
That's cool, I actually tested `3.7.1-rc1` (via CWP 1.9.0-rc1 & `--ignore-platform-reqs`) and:
```
[Fri Jun 29 09:03:30.827492 2018] [php7:error] [pid 1280] [client 10.0.2.2:62290] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /srv/http/summy/framework/core/compat/Object.php on line 3
```
anyway.

Is there something one is supposed to do in order to enable support for the class aliasing?

**Comment by robbieaverill** [comment]
We could do this: https://docs.silverstripe.org/en/3/changelogs/3.7.0#for-module-authors

**Comment by robbieaverill** [comment]
Re-triaged as a bug

**Comment by robbieaverill** [comment]
Re-triaged again as an enhancement

**Comment by snoopy4ever** [comment]
Hi Guys,

I've been googling for 3 days now, I have SS 3.7.3 installed and PHP 7.2 on the server, I cannot bypass this error, I've tried everything and slowly giving up :(

Fatal error: Cannot use 'Object' as class name as it is reserved in /home/devonp/framework/core/compat/Object.php on line 3

Any idea how and where to apply any hotfix? Website was working good on my sandbox (PHP 5.6) now I'm moving this to the actual hosting and cannot get this working, anyone please?

Regards,
Peter.

**Comment by robbieaverill** [comment]
Hi @snoopy4ever, there'll be a fix for you to use in a couple of hours. You won't be able to workaround it without forking the module, or waiting for the update to be merged - sorry.

**Comment by snoopy4ever** [comment]
Wow! Thank you Rob! Really I do appreciate that, I will wait, sound like a salvation to me, really whole weekend trying to get this running on this hosting, seen a lot of similar threads (some of them seem to be old and stale) and seen also this one few times and then again but with your comment that brought a hope in my hearth ❤️

**Comment by robbieaverill** [comment]
No problem, you caught me while I was working on it =)

I'll be pushing the new branches up once GitHub is fully operational again (it's having [some issues](https://www.githubstatus.com/) at the moment).

**Comment by robbieaverill** [comment]
PR at https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/45

**Comment by ScopeyNZ** [comment]
#45 is merged
