### ISSUE TITLE
Module will break if running on a project that has private repositories without authentication

### ISSUE THREAD

**Issue by robbieaverill** [bringyourownideas/silverstripe-composer-update-checker#37]
If your project has some modules using private repositories in it, the whole silverstripe-maintenance module report generation will fail if authentication fails.

Example: CWP web servers don't contain their SSH deploy key, so cannot fetch information from the private repositories that they initially deployed using this SSH key.

Current situation is that the report generation task will fail with an error referencing not being able to clone the private repository.

A short term fix for this is to allow individual module info fetches to fail gracefully and allow the rest of the report generation to complete as usual. My assumption is that the data from silverstripe-maintenance's report would still be shown in the report (the name, description and version installed) but you wouldn't get the next available versions listed for it.

## Pull requests

- [x] 1.0: #40 
- [x] 2.0: #39

**Comment by ScopeyNZ** [comment]
Both the PRs have been merged 👍
