### ISSUE TITLE
Output options

### ISSUE THREAD

**Issue by spekulatius** [bringyourownideas/silverstripe-composer-update-checker#7]
Output of the results as a json would be a nice to have. This should be secured by a token.

**Comment by robbieaverill** [comment]
@spekulatius do you see this as a command line argument, or a HTTP API endpoint, or both?

**Comment by spekulatius** [comment]
Hello @robbieaverill 

originally a API endpoint was my plan (as far as I remember). With the great work on the maintenance module I would say we can close this. Let me know if you think we still need it and I'll reopen it.

Cheers,
Peter
